#!/usr/bin/python
import commands
import sys
import os
FILECONTEXTDIR="/etc/security/selinux/src/policy/"

def getUsers():
	rc=commands.getstatusoutput("grep ^user %s/users" % FILECONTEXTDIR)
	udict={}
	if rc[0] == 0:
		ulist=rc[1].strip().split("\n")
		for u in ulist:
			user=u.split()
			if user[1]=="root" or user[1]=="user_u" or user[1]=="system_u":
				continue
			role = user[4].split("_r")[0]
			if role == "user":
				continue
			udict[user[1]]=role
	return udict

def usage(error=""):
	if error != "":
		print error
	print "Usage: %s FILE_CONTEXTS" % sys.argv[0]
	sys.exit(1)
	
def update(filecontext, user, role):
	rc=commands.getstatusoutput("grep -h '/home/\[\^' %s | grep -v vmware | sed -e 's|/home/\[\^\/\]+|/home/%s|g' -e 's/user/%s/' -e 's/system_u/%s/'" % (filecontext, user, role, user))
	if rc[0] == 0:
		print rc[1]
	else:
		usage(rc[1])
	return rc

try:
	users=getUsers()
	for u in users.keys():
		update(sys.argv[1], u, users[u]) 
except ValueError, error:
	usage(error)
except IndexError, error:
	usage()
	
