#!/bin/sh 
if [ $# == 0 ]; then
    echo "usage: $0 path ..."
    exit 1
fi
make -C /etc/security/selinux/src/policy file_contexts/file_contexts 2&>1 > /dev/null
echo $@ | tr " " "\n" | /usr/sbin/setfiles -v -s /etc/security/selinux/src/policy/file_contexts/file_contexts 2> /dev/null 
